In [1]:
!pip install tensorflow

In [2]:
import tensorflow as tf


In [3]:
print(tf.__version__)

2.20.0


In [6]:
#Scalar 
x = 6 
print(x)

x_tesnor = tf.constant(6)
print(x_tesnor)

6
tf.Tensor(6, shape=(), dtype=int32)


In [10]:
#it saves operation in memory as x_tensor+10 not perform untill it performs any operation on it 
x_tesnor+10
y_tensor  = x_tesnor+10
print(y_tensor)

tf.Tensor(16, shape=(), dtype=int32)


In [11]:
print(x_tesnor+10)

tf.Tensor(16, shape=(), dtype=int32)


In [13]:
# 0D tensor (scalar)
t0 = tf.constant(7)
# 1D tensor (vector)
t1 = tf.constant([1,2,3,4])
# 2D tensor (matrix)
t2 = tf.constant([[1,2],[3,4]])
# 3D tensor(cube/stack of matrix)
t3 = tf.constant([[[1],[2]],[[3],[4]]])
print(t0.shape,t1.shape,t2.shape,t3.shape)

() (4,) (2, 2) (2, 2, 1)


In [ ]:
x =tf.constant([[1.0,2.0],[4.0,5.0]])
y = tf.constant([[5.0,6.0],[7.0,8.0]])


In [15]:
#element wise operation

print("Add:\n",x+y)
print("subtract:\n",x-y)
print("Multiply:\n",x*y)

Add:
 tf.Tensor(
[[ 6.  8.]
 [11. 13.]], shape=(2, 2), dtype=float32)
subtract:
 tf.Tensor(
[[-4. -4.]
 [-3. -3.]], shape=(2, 2), dtype=float32)
Multiply:
 tf.Tensor(
[[ 5. 12.]
 [28. 40.]], shape=(2, 2), dtype=float32)


In [16]:
#matrix multiplicaton 
print("Matrix Multiplication:\n",tf.matmul(x,y))

Matrix Multiplication:
 tf.Tensor(
[[19. 22.]
 [55. 64.]], shape=(2, 2), dtype=float32)


In [17]:
#keras -> It is build on the top of tensorflow 
#Two ways of making model 
#1.Sequential
#2.Fational